plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fexed.spacecadetpinball'
    compileSdk 36

    defaultConfig {
        applicationId "com.fexed.spacecadetpinball"
        minSdk 21
        targetSdk 36
        versionCode 13
        versionName "2.5"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    lint {
        abortOnError false
    }

    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'

        unitTests.all {
            useJUnitPlatform()
        }
    }

    packaging {
        resources {
            excludes += ['META-INF/*']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'androidx.test:core:1.5.0'
    androidTestUtil 'androidx.test:orchestrator:1.4.2'
    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-engine:5.7.1'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
